### ISSUE TITLE
Don't default to a specific JuliaFormatter version

### ISSUE THREAD

**Issue by avik-pal** [SciML/.github#14]
https://github.com/SciML/.github/blob/736f392c1e5fed7f167ea810e099077d96a66b7f/.github/workflows/format-check.yml#L18

will force formatting using an older version, unless we opt in to not do so.

**Comment by ChrisRackauckas** [comment]
Yes we should let it update

**Comment by ChrisRackauckas** [comment]
does floating work here?

**Comment by thazhemadam** [comment]
Yes, having this be `1` should work.

**Comment by thazhemadam** [comment]
Resolved in #17.
