### ISSUE TITLE
PR templates not showing up on repos?

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/.github#5]
**Describe the bug 🐞**

The PR templates are not showing up in the downstream repos. @prbzrg can you take a look to see if I did anything wrong?

**Comment by prbzrg** [comment]
I looked into it.
It looks like for PRs, if there is `.github/pull_request_template.md` it will be used but for multiple templates in `.github/PULL_REQUEST_TEMPLATE`, query parameter `template` is the way.
For example:
https://github.com/SciML/.github/compare/master...ChrisRackauckas-patch-1?quick_pull=1&template=bugfix.md


For more info, see:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request

**Comment by prbzrg** [comment]
Some other PR template examples:
https://github.com/devspace/awesome-github-templates?tab=readme-ov-file#rocket-templates-for-pull-requests

**Comment by ChrisRackauckas** [comment]
It looks like that stuff just doesn't have the header part, but I don't see how that would fix it not showing up?

> https://github.com/SciML/.github/compare/master...ChrisRackauckas-patch-1?quick_pull=1&template=bugfix.md

how did you do that? When I opened a PR I didn't have a choice of template.

**Comment by prbzrg** [comment]
Just add it to the URL.
I looked more about it and found this:
https://github.com/orgs/community/discussions/4620
